#!/bin/bash


set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE $POSTGRES_USER WITH LOGIN PASSWORD '$POSTGRES_PASSWORD';
  ALTER ROLE $POSTGRES_USER WITH SUPERUSER;
  CREATE DATABASE $POSTGRES_DB_NAME ENCODING 'UTF-8';
EOSQL